name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      #- uses: actions/checkout@v2
      #- uses: actions/setup-node@v2
      #  with:
      #    node-version: "14"
      #- name: npm install
      #  run: npm install
      #- name: lint
      #  run: npm run eslint
      #- name: test
      # run: npm run test
      - name: ver eventos
        run: echo "github.event_name"
      #- name: Bump version and push tag
      #  if: ${{ github.event_name == 'pull_request' }}
      #  uses: anothrNick/github-tag-action@1.33.0
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    WITH_V: truncate
      #- name: deploy site to vercel
      #  if: ${{ github.event_name == 'pull_request' }}
      #  uses: amondnet/vercel-action@v20
      #  with:
      #    vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
      #    github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
      #    vercel-args: "--prod" #Optional
      #    vercel-org-id: ${{ secrets.ORG_ID}} #Required
      #    vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
